# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-21 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kata', '0004_auto_20171008_0925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kataround',
            options={'ordering': ['round', 'order']},
        ),
    ]
