# Generated by Django 2.1.8 on 2019-05-12 20:36

from django.db import migrations, models
import kata.models


class Migration(migrations.Migration):

    dependencies = [
        ('kata', '0007_auto_20180126_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katamatch',
            name='combined_score',
            field=models.DecimalField(blank=True, decimal_places=1, editable=False, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='katamatch',
            name='score1',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[kata.models.validate_score]),
        ),
        migrations.AlterField(
            model_name='katamatch',
            name='score2',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[kata.models.validate_score]),
        ),
        migrations.AlterField(
            model_name='katamatch',
            name='score3',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[kata.models.validate_score]),
        ),
        migrations.AlterField(
            model_name='katamatch',
            name='score4',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[kata.models.validate_score]),
        ),
        migrations.AlterField(
            model_name='katamatch',
            name='score5',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[kata.models.validate_score]),
        ),
        migrations.AlterField(
            model_name='katamatch',
            name='tie_score',
            field=models.DecimalField(blank=True, decimal_places=1, editable=False, max_digits=3, null=True),
        ),
    ]
