# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 23:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField()),
                ('aka_won', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MatchPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('points', models.PositiveSmallIntegerField()),
                ('disqualified', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='aka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='bracket.MatchPerson'),
        ),
        migrations.AddField(
            model_name='match',
            name='consolation_match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='bracket.Match'),
        ),
        migrations.AddField(
            model_name='match',
            name='shiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='bracket.MatchPerson'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner_match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='bracket.Match'),
        ),
    ]
