# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0002_match_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='aka',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='bracket.MatchPerson'),
        ),
        migrations.AlterField(
            model_name='match',
            name='shiro',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='bracket.MatchPerson'),
        ),
    ]
