# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0003_auto_20170521_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchperson',
            name='points',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
