# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0007_auto_20170521_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bracket1Elim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consolation_match', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='bracket.Match')),
                ('final_match', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='bracket.Match')),
            ],
        ),
    ]
