# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0008_bracket1elim'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='bracket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bracket.Bracket1Elim'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='round',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='consolation_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bracket.Match'),
        ),
        migrations.AlterField(
            model_name='match',
            name='order',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bracket.Match'),
        ),
    ]
