# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0009_auto_20170521_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracket1elim',
            name='consolation_match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bracket.Match'),
        ),
        migrations.AlterField(
            model_name='bracket1elim',
            name='final_match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bracket.Match'),
        ),
    ]
