# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0011_auto_20170521_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracket1elim',
            name='name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
