# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0012_bracket1elim_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-round', 'order']},
        ),
        migrations.AddField(
            model_name='bracket1elim',
            name='people',
            field=models.ManyToManyField(to='bracket.MatchPerson'),
        ),
    ]
