# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0013_auto_20170521_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracket1elim',
            name='rounds',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
