# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-20 09:11
from __future__ import unicode_literals

from django.db import migrations

def make_groups(apps, schema_editors):
    pass


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(make_groups),
    ]
