# Generated by Django 2.1.5 on 2019-01-26 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rightssupport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rightssupport',
            options={'managed': False, 'permissions': (('view', '=> Read only access'), ('edit', '=> Edit non-administrative data'), ('admin', '=> Edit all data'))},
        ),
    ]
