# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kumite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kumitematch',
            name='aka',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='kumite.KumiteMatchPerson'),
        ),
        migrations.AlterField(
            model_name='kumitematch',
            name='shiro',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='kumite.KumiteMatchPerson'),
        ),
    ]
