# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-22 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_event_format'),
        ('kumite', '0004_kumiteelim1bracket_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='kumitematchperson',
            name='eventlink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='registration.EventLink'),
        ),
    ]
