# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-23 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kumite', '0007_auto_20170922_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kumitematch',
            old_name='bracket',
            new_name='bracket_elim1',
        ),
    ]
