# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-24 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_division_state'),
        ('kumite', '0009_remove_kumiteelim1bracket_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kumite2People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='registration.Division')),
                ('loser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='registration.EventLink')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='registration.EventLink')),
            ],
        ),
    ]
