# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-11 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kumite', '0014_kumitematchperson_is_first_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='kumitematch',
            name='swap',
            field=models.BooleanField(default=False),
        ),
    ]
