# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KumiteElim1Bracket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('rounds', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='KumiteMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.SmallIntegerField()),
                ('order', models.SmallIntegerField()),
                ('done', models.BooleanField(default=False)),
                ('aka_won', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-round', 'order'],
            },
        ),
        migrations.CreateModel(
            name='KumiteMatchPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('points', models.PositiveSmallIntegerField(default=0)),
                ('disqualified', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='kumitematch',
            name='aka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='kumite.KumiteMatchPerson'),
        ),
        migrations.AddField(
            model_name='kumitematch',
            name='bracket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kumite.KumiteElim1Bracket'),
        ),
        migrations.AddField(
            model_name='kumitematch',
            name='consolation_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='kumite.KumiteMatch'),
        ),
        migrations.AddField(
            model_name='kumitematch',
            name='shiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='kumite.KumiteMatchPerson'),
        ),
        migrations.AddField(
            model_name='kumitematch',
            name='winner_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='kumite.KumiteMatch'),
        ),
        migrations.AddField(
            model_name='kumiteelim1bracket',
            name='people',
            field=models.ManyToManyField(to='kumite.KumiteMatchPerson'),
        ),
    ]
