# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-22 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_event_format'),
        ('kumite', '0003_kumitematchperson_warnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='kumiteelim1bracket',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='registration.Division'),
        ),
    ]
