# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-22 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kumite', '0005_kumitematchperson_eventlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kumitematchperson',
            name='name',
        ),
    ]
