# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-22 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kumite', '0006_remove_kumitematchperson_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kumitematchperson',
            name='eventlink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='registration.EventLink'),
        ),
    ]
