# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-24 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kumite', '0008_auto_20170923_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kumiteelim1bracket',
            name='people',
        ),
    ]
