# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-06 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kumite', '0012_auto_20170928_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kumitematchperson',
            name='eventlink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.EventLink'),
        ),
        migrations.AlterField(
            model_name='kumiteroundrobinbracket',
            name='bronze',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='registration.EventLink'),
        ),
        migrations.AlterField(
            model_name='kumiteroundrobinbracket',
            name='gold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='registration.EventLink'),
        ),
        migrations.AlterField(
            model_name='kumiteroundrobinbracket',
            name='silver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='registration.EventLink'),
        ),
    ]
