# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 12:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('MF', 'Combined')], max_length=2)),
                ('start_age', models.PositiveSmallIntegerField()),
                ('stop_age', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EventLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.Division')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.PositiveSmallIntegerField()),
                ('instructor', models.CharField(max_length=200)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('reg_date', models.DateField(default=datetime.date.today, verbose_name='Date registered')),
                ('paid', models.BooleanField(default=False)),
                ('paidDate', models.DateField(blank=True, null=True, verbose_name='Date paid')),
                ('notes', models.TextField(blank=True, max_length=512)),
                ('events', models.ManyToManyField(related_name='person2', through='registration.EventLink', to='registration.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='person',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.Rank'),
        ),
        migrations.AddField(
            model_name='eventlink',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Person'),
        ),
        migrations.AddField(
            model_name='division',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.Event'),
        ),
        migrations.AddField(
            model_name='division',
            name='start_rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='registration.Rank'),
        ),
        migrations.AddField(
            model_name='division',
            name='stop_rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='registration.Rank'),
        ),
    ]
