# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 13:05
from __future__ import unicode_literals

from django.db import migrations


def load_stores_from_fixture(apps, schema_editor):
    from django.core.management import call_command
    call_command("loaddata", "rank.json")


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_stores_from_fixture),
    ]
