# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20170527_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='order',
            field=models.SmallIntegerField(unique=True),
        ),
    ]
