# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-18 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20170527_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlink',
            name='manual_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='eventlink',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.Person'),
        ),
    ]
