# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-05 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20170924_0900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventlink',
            options={'ordering': ('event__name',)},
        ),
    ]
