# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-26 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_auto_20180124_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='parent',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
