# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-26 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_person_checked in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='Checked in',
        ),
        migrations.AddField(
            model_name='person',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Checked in'),
        ),
    ]
