# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_eventlink_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlink',
            name='disqualified',
            field=models.BooleanField(default=False),
        ),
    ]
