# Generated by Django 2.1.5.dev20181231203541 on 2019-01-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_auto_20181231_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='teammates',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
