# Generated by Django 2.2.1 on 2019-05-11 10:30

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0019_person_teammates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='division',
            options={'ordering': ['event__is_team', 'start_age', 'start_rank', 'event']},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': [django.db.models.functions.text.Lower('last_name'), django.db.models.functions.text.Lower('first_name')]},
        ),
    ]
