# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.PositiveSmallIntegerField()),
                ('instructor', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('reg_date', models.DateTimeField(verbose_name='Date registered')),
                ('paidDate', models.DateTimeField(verbose_name='Date paid')),
                ('notes', models.TextField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.Rank'),
        ),
    ]
