# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 19:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='notes',
            field=models.TextField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='person',
            name='paidDate',
            field=models.DateField(verbose_name='Date paid'),
        ),
        migrations.AlterField(
            model_name='person',
            name='reg_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date registered'),
        ),
    ]
