# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20170421_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='paidDate',
            field=models.DateField(blank=True, null=True, verbose_name='Date paid'),
        ),
    ]
