# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20170421_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
