# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-22 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_event_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
