# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20170421_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='events',
            field=models.ManyToManyField(to='registration.Event'),
        ),
    ]
