# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 23:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_person_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_age', models.PositiveSmallIntegerField()),
                ('stop_age', models.PositiveSmallIntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.Event')),
                ('start_rank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.Rank')),
            ],
        ),
        migrations.CreateModel(
            name='EventLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='registration.Division')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.Event')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Person')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='events2',
            field=models.ManyToManyField(related_name='person2', through='registration.EventLink', to='registration.Event'),
        ),
    ]
