# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-24 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_division_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='format',
            field=models.CharField(choices=[('A', 'kata'), ('B', 'elim1')], max_length=1),
        ),
    ]
