# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 23:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20170421_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='stop_rank',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='registration.Rank'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='division',
            name='start_rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='registration.Rank'),
        ),
    ]
