# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_auto_20170421_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('MF', 'Combined')], default='MF', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventlink',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.Division'),
        ),
    ]
