# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 01:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_auto_20170422_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='events',
        ),
    ]
