# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-26 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_person_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='parent',
            field=models.CharField(blank=True, max_length=100, verbose_name='Parent or Guardian (if under 18)'),
        ),
    ]
