# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 01:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_remove_person_events'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='events2',
            new_name='events',
        ),
    ]
