# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_auto_20170422_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default="", max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
