# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-26 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_auto_20180126_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Checked in',
            field=models.BooleanField(default=False),
        ),
    ]
