# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import kata.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('score1', models.FloatField(validators=[kata.models.validate_score])),
                ('score2', models.FloatField(validators=[kata.models.validate_score])),
                ('score3', models.FloatField(validators=[kata.models.validate_score])),
                ('score4', models.FloatField(validators=[kata.models.validate_score])),
                ('score5', models.FloatField(validators=[kata.models.validate_score])),
                ('combined_score', models.FloatField(editable=False)),
                ('tie_score', models.FloatField(editable=False)),
            ],
            options={
                'ordering': ['-combined_score', '-tie_score'],
            },
        ),
    ]
