# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-08 00:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kata', '0002_auto_20171007_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katabracket',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.Division'),
        ),
    ]
