# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-26 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kata', '0006_delete_scoring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katamatch',
            name='eventlink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.EventLink'),
        ),
    ]
