# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 13:43
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('tmp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myaddress',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default=0, max_length=128),
            preserve_default=False,
        ),
    ]
